<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Kalnoy\Nestedset\NodeTrait;

class Category extends Model
{
    use NodeTrait;
    protected $fillable = [
        'name',
        'parent_id'
    ];

    public function items()
    {
        return $this->hasMany(Item::class);
    }

    public function delete()
    {
        foreach ($this->items as $item) {
            $item->delete();
        }
        return parent::delete(); // TODO: Change the autogenerated stub
    }
}
